# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lrx/MyClamAv/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.full_scan = QtWidgets.QPushButton(self.centralwidget)
        self.full_scan.setGeometry(QtCore.QRect(50, 30, 151, 81))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/lrx/MyClamAv/icon/full_scan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.full_scan.setIcon(icon)
        self.full_scan.setIconSize(QtCore.QSize(40, 40))
        self.full_scan.setObjectName("full_scan")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(300, 260, 161, 81))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/lrx/MyClamAv/icon/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon1)
        self.settings.setIconSize(QtCore.QSize(40, 40))
        self.settings.setObjectName("settings")
        self.update_db = QtWidgets.QPushButton(self.centralwidget)
        self.update_db.setGeometry(QtCore.QRect(50, 140, 151, 81))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/lrx/MyClamAv/icon/update_db.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_db.setIcon(icon2)
        self.update_db.setIconSize(QtCore.QSize(40, 40))
        self.update_db.setObjectName("update_db")
        self.file_scan = QtWidgets.QPushButton(self.centralwidget)
        self.file_scan.setGeometry(QtCore.QRect(300, 30, 161, 81))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/lrx/MyClamAv/icon/file_scan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_scan.setIcon(icon3)
        self.file_scan.setIconSize(QtCore.QSize(40, 40))
        self.file_scan.setObjectName("file_scan")
        self.blackmail = QtWidgets.QPushButton(self.centralwidget)
        self.blackmail.setGeometry(QtCore.QRect(300, 140, 161, 81))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/lrx/MyClamAv/icon/black_mail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blackmail.setIcon(icon4)
        self.blackmail.setIconSize(QtCore.QSize(40, 40))
        self.blackmail.setObjectName("blackmail")
        self.url_scan = QtWidgets.QPushButton(self.centralwidget)
        self.url_scan.setGeometry(QtCore.QRect(50, 260, 151, 81))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/lrx/MyClamAv/icon/url.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.url_scan.setIcon(icon5)
        self.url_scan.setIconSize(QtCore.QSize(40, 40))
        self.url_scan.setObjectName("url_scan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ClamAv"))
        self.full_scan.setText(_translate("MainWindow", "全局扫描"))
        self.settings.setText(_translate("MainWindow", "设置"))
        self.update_db.setText(_translate("MainWindow", "更新病毒库"))
        self.file_scan.setText(_translate("MainWindow", "扫描文件"))
        self.blackmail.setText(_translate("MainWindow", "勒索软件扫描"))
        self.url_scan.setText(_translate("MainWindow", "可疑url扫描"))
